'use strict';
const desingLegend = document.querySelector('.js-design-legend');
const fillLegend = document.querySelector('.js-fill-legend');
const shareLegend = document.querySelector('.js-share-legend');
const desingContent = document.querySelector('.js-design-content');
const fillContent = document.querySelector('.js-fill-content');
const shareContent = document.querySelector('.js-share-content');
const fillRotateScroll = document.querySelector('.js-fill-rotate-scroll');
const designRotateScroll = document.querySelector('.js-designRotateScroll');
const shareRotateScroll = document.querySelector('.js-share-rotate-scroll');
